### ISSUE TITLE
For some reason my brackets are colored yellow and purple

### ISSUE THREAD

**Issue by AHTOOOXA** [nparamonov/vscode-cold-python-theme#10]
![CleanShot 2024-07-16 at 08 48 04@2x](https://github.com/user-attachments/assets/cccd3f17-846f-48fb-9f11-427cfc17669f)

**Comment by AHTOOOXA** [comment]
you may add 
```"editor.bracketPairColorization.enabled": false,```
to theme settings

**Comment by nparamonov** [comment]
Thanks! I can't add this to the theme json, but I'll write it in the readme
