### ISSUE TITLE
.yml sometimes without color

### ISSUE THREAD

**Issue by AtticusZeller** [nparamonov/vscode-cold-python-theme#12]
thanks for design the gorgours theme,icon ,fronts! i do love the blue color as function name,
![image](https://github.com/user-attachments/assets/314b5a3b-4c6d-4366-95f7-5fa721036a50)
,which is same to pycharm!
but here is a issues about .yml file color,sometimes work or not

docker-compose.yml works good
![image](https://github.com/user-attachments/assets/6850818a-9c32-4acf-99d9-99f8ed2618f1)
but .pre-commit-config.yml without color 
![image](https://github.com/user-attachments/assets/365ec16c-35bd-45c8-b989-2484b75fff86)

**Comment by nparamonov** [comment]
Hi @Atticuszz . This is strange. The rules for any yml files are the same.

![image](https://github.com/user-attachments/assets/25235a07-984a-47e3-8990-58c982fb803b)

I assume that some extension redefines syntax tokens in its own way, and because of this the theme does not have the required colors.

Do you have any pre commit extensions installed? If you let me know, I'll try to add their tokens to the theme.

**Comment by AtticusZeller** [comment]
@nparamonov thanks for your patient reply! i have not installed any pre commit extensions installed,now it fixed by disable all extension in vscode and enable it first and then another to check if any extension interupt the theme,so werid that it works normally thought enable all extension step by step. if somebody find not work ,they can try to  `disable all extension ` and `enable it again`
but now there is another isssue regards to [`uv.lock`](https://github.com/Atticuszz/full-stack-fastapi-template/blob/uv/backend/uv.lock),
![image](https://github.com/user-attachments/assets/2a5f8be3-2ca5-41ca-95bc-52236de43c49)
 which content is almost same to [`poetry.lock`](https://github.com/Atticuszz/full-stack-fastapi-template/blob/uv/backend/poetry.lock),also ,it's fun to find that `uv.lock` without color in github page but `poetry.lock` is ok haha

**Comment by nparamonov** [comment]
The problem with `uv.lock` is that VS Code doesn't recognize it (although the syntax is really the same as `poetry.lock` - toml).

In theory, as soon as VS Code starts supporting these files, the required styles from the theme will be applied automatically.

**Comment by AtticusZeller** [comment]
Got it ，Thanks for explanation of `uv.lock`!
